from __future__ import annotations

import flatbuffers
import numpy as np

import flatbuffers
import typing
from flatbuffers import table

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class DType(object):
  UNKNOWN: int
  BOOL: int
  UINT8: int
  INT4: int
  INT8: int
  INT16: int
  INT32: int
  INT48: int
  FP32: int
  UINT16: int
  FP16: int
  BF16: int
  SHAPE: int
  FP8E4M3: int
  FP8E5M2: int
class ResizeMode(object):
  UNKNOWN: int
  NEAREST: int
  BILINEAR: int
class NanPropagationMode(object):
  UNKNOWN: int
  PROPAGATE: int
  IGNORE: int
class Op(object):
  UNKNOWN: int
  ARGMAX: int
  AVG_POOL2D: int
  CONV2D: int
  CONV3D: int
  DEPTHWISE_CONV2D: int
  FULLY_CONNECTED: int
  MATMUL: int
  MAX_POOL2D: int
  TRANSPOSE_CONV2D: int
  CLAMP: int
  RESERVED: int
  SIGMOID: int
  TANH: int
  ADD: int
  ARITHMETIC_RIGHT_SHIFT: int
  BITWISE_AND: int
  BITWISE_OR: int
  BITWISE_XOR: int
  INTDIV: int
  LOGICAL_AND: int
  LOGICAL_LEFT_SHIFT: int
  LOGICAL_RIGHT_SHIFT: int
  LOGICAL_OR: int
  LOGICAL_XOR: int
  MAXIMUM: int
  MINIMUM: int
  MUL: int
  POW: int
  SUB: int
  TABLE: int
  ABS: int
  BITWISE_NOT: int
  CEIL: int
  CLZ: int
  EXP: int
  FLOOR: int
  LOG: int
  LOGICAL_NOT: int
  NEGATE: int
  RECIPROCAL: int
  RSQRT: int
  SELECT: int
  EQUAL: int
  GREATER: int
  GREATER_EQUAL: int
  REDUCE_ANY: int
  REDUCE_ALL: int
  REDUCE_MAX: int
  REDUCE_MIN: int
  REDUCE_PRODUCT: int
  REDUCE_SUM: int
  CONCAT: int
  PAD: int
  RESHAPE: int
  REVERSE: int
  SLICE: int
  TILE: int
  TRANSPOSE: int
  GATHER: int
  SCATTER: int
  RESIZE: int
  CAST: int
  RESCALE: int
  CONST: int
  IDENTITY: int
  CUSTOM: int
  COND_IF: int
  WHILE_LOOP: int
  FFT2D: int
  RFFT2D: int
  ERF: int
  DIM: int
  CONST_SHAPE: int
  CONCAT_SHAPE: int
  ADD_SHAPE: int
  SUB_SHAPE: int
  MUL_SHAPE: int
  DIV_SHAPE: int
  COS: int
  SIN: int
class Attribute(object):
  NONE: int
  PoolAttribute: int
  ConvAttribute: int
  TransposeConvAttribute: int
  PadAttribute: int
  AxisAttribute: int
  ResizeAttribute: int
  ClampAttribute: int
  RescaleAttribute: int
  MulAttribute: int
  ArithmeticRightShiftAttribute: int
  CondIfAttribute: int
  WhileLoopAttribute: int
  TransposeAttribute: int
  TableAttribute: int
  MatMulAttribute: int
  FullyConnectedAttribute: int
  NegateAttribute: int
  CustomAttribute: int
  FFTAttribute: int
  RFFTAttribute: int
  NanPropagationAttribute: int
def AttributeCreator(union_type: typing.Literal[Attribute.NONE, Attribute.PoolAttribute, Attribute.ConvAttribute, Attribute.TransposeConvAttribute, Attribute.PadAttribute, Attribute.AxisAttribute, Attribute.ResizeAttribute, Attribute.ClampAttribute, Attribute.RescaleAttribute, Attribute.MulAttribute, Attribute.ArithmeticRightShiftAttribute, Attribute.CondIfAttribute, Attribute.WhileLoopAttribute, Attribute.TransposeAttribute, Attribute.TableAttribute, Attribute.MatMulAttribute, Attribute.FullyConnectedAttribute, Attribute.NegateAttribute, Attribute.CustomAttribute, Attribute.FFTAttribute, Attribute.RFFTAttribute, Attribute.NanPropagationAttribute], table: table.Table) -> typing.Union[None, PoolAttribute, ConvAttribute, TransposeConvAttribute, PadAttribute, AxisAttribute, ResizeAttribute, ClampAttribute, RescaleAttribute, MulAttribute, ArithmeticRightShiftAttribute, CondIfAttribute, WhileLoopAttribute, TransposeAttribute, TableAttribute, MatMulAttribute, FullyConnectedAttribute, NegateAttribute, CustomAttribute, FFTAttribute, RFFTAttribute, NanPropagationAttribute]: ...
class PoolAttribute(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> PoolAttribute: ...
  @classmethod
  def GetRootAsPoolAttribute(cls, buf: bytes, offset: int) -> PoolAttribute: ...
  @classmethod
  def PoolAttributeBufferHasIdentifier(cls, buf: bytes, offset: int, size_prefixed: bool) -> bool: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Pad(self, i: int) -> typing.List[int]: ...
  def PadAsNumpy(self) -> np.ndarray: ...
  def PadLength(self) -> int: ...
  def PadIsNone(self) -> bool: ...
  def Kernel(self, i: int) -> typing.List[int]: ...
  def KernelAsNumpy(self) -> np.ndarray: ...
  def KernelLength(self) -> int: ...
  def KernelIsNone(self) -> bool: ...
  def Stride(self, i: int) -> typing.List[int]: ...
  def StrideAsNumpy(self) -> np.ndarray: ...
  def StrideLength(self) -> int: ...
  def StrideIsNone(self) -> bool: ...
  def InputZp(self) -> int: ...
  def OutputZp(self) -> int: ...
  def AccType(self) -> typing.Literal[DType.UNKNOWN, DType.BOOL, DType.UINT8, DType.INT4, DType.INT8, DType.INT16, DType.INT32, DType.INT48, DType.FP32, DType.UINT16, DType.FP16, DType.BF16, DType.SHAPE, DType.FP8E4M3, DType.FP8E5M2]: ...
  def NanMode(self) -> typing.Literal[NanPropagationMode.UNKNOWN, NanPropagationMode.PROPAGATE, NanPropagationMode.IGNORE]: ...
class PoolAttributeT(object):
  pad: typing.List[int]
  kernel: typing.List[int]
  stride: typing.List[int]
  inputZp: int
  outputZp: int
  accType: typing.Literal[DType.UNKNOWN, DType.BOOL, DType.UINT8, DType.INT4, DType.INT8, DType.INT16, DType.INT32, DType.INT48, DType.FP32, DType.UINT16, DType.FP16, DType.BF16, DType.SHAPE, DType.FP8E4M3, DType.FP8E5M2]
  nanMode: typing.Literal[NanPropagationMode.UNKNOWN, NanPropagationMode.PROPAGATE, NanPropagationMode.IGNORE]
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> PoolAttributeT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> PoolAttributeT: ...
  @classmethod
  def InitFromObj(cls, poolAttribute: PoolAttribute) -> PoolAttributeT: ...
  def _UnPack(self, poolAttribute: PoolAttribute) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def PoolAttributeStart(builder: flatbuffers.Builder) -> None: ...
def PoolAttributeAddPad(builder: flatbuffers.Builder, pad: uoffset) -> None: ...
def PoolAttributeStartPadVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def PoolAttributeAddKernel(builder: flatbuffers.Builder, kernel: uoffset) -> None: ...
def PoolAttributeStartKernelVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def PoolAttributeAddStride(builder: flatbuffers.Builder, stride: uoffset) -> None: ...
def PoolAttributeStartStrideVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def PoolAttributeAddInputZp(builder: flatbuffers.Builder, inputZp: int) -> None: ...
def PoolAttributeAddOutputZp(builder: flatbuffers.Builder, outputZp: int) -> None: ...
def PoolAttributeAddAccType(builder: flatbuffers.Builder, accType: typing.Literal[DType.UNKNOWN, DType.BOOL, DType.UINT8, DType.INT4, DType.INT8, DType.INT16, DType.INT32, DType.INT48, DType.FP32, DType.UINT16, DType.FP16, DType.BF16, DType.SHAPE, DType.FP8E4M3, DType.FP8E5M2]) -> None: ...
def PoolAttributeAddNanMode(builder: flatbuffers.Builder, nanMode: typing.Literal[NanPropagationMode.UNKNOWN, NanPropagationMode.PROPAGATE, NanPropagationMode.IGNORE]) -> None: ...
def PoolAttributeEnd(builder: flatbuffers.Builder) -> uoffset: ...
class ConvAttribute(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> ConvAttribute: ...
  @classmethod
  def GetRootAsConvAttribute(cls, buf: bytes, offset: int) -> ConvAttribute: ...
  @classmethod
  def ConvAttributeBufferHasIdentifier(cls, buf: bytes, offset: int, size_prefixed: bool) -> bool: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Pad(self, i: int) -> typing.List[int]: ...
  def PadAsNumpy(self) -> np.ndarray: ...
  def PadLength(self) -> int: ...
  def PadIsNone(self) -> bool: ...
  def Stride(self, i: int) -> typing.List[int]: ...
  def StrideAsNumpy(self) -> np.ndarray: ...
  def StrideLength(self) -> int: ...
  def StrideIsNone(self) -> bool: ...
  def Dilation(self, i: int) -> typing.List[int]: ...
  def DilationAsNumpy(self) -> np.ndarray: ...
  def DilationLength(self) -> int: ...
  def DilationIsNone(self) -> bool: ...
  def LocalBound(self) -> bool: ...
  def AccType(self) -> typing.Literal[DType.UNKNOWN, DType.BOOL, DType.UINT8, DType.INT4, DType.INT8, DType.INT16, DType.INT32, DType.INT48, DType.FP32, DType.UINT16, DType.FP16, DType.BF16, DType.SHAPE, DType.FP8E4M3, DType.FP8E5M2]: ...
class ConvAttributeT(object):
  pad: typing.List[int]
  stride: typing.List[int]
  dilation: typing.List[int]
  localBound: bool
  accType: typing.Literal[DType.UNKNOWN, DType.BOOL, DType.UINT8, DType.INT4, DType.INT8, DType.INT16, DType.INT32, DType.INT48, DType.FP32, DType.UINT16, DType.FP16, DType.BF16, DType.SHAPE, DType.FP8E4M3, DType.FP8E5M2]
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> ConvAttributeT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> ConvAttributeT: ...
  @classmethod
  def InitFromObj(cls, convAttribute: ConvAttribute) -> ConvAttributeT: ...
  def _UnPack(self, convAttribute: ConvAttribute) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def ConvAttributeStart(builder: flatbuffers.Builder) -> None: ...
def ConvAttributeAddPad(builder: flatbuffers.Builder, pad: uoffset) -> None: ...
def ConvAttributeStartPadVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def ConvAttributeAddStride(builder: flatbuffers.Builder, stride: uoffset) -> None: ...
def ConvAttributeStartStrideVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def ConvAttributeAddDilation(builder: flatbuffers.Builder, dilation: uoffset) -> None: ...
def ConvAttributeStartDilationVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def ConvAttributeAddLocalBound(builder: flatbuffers.Builder, localBound: bool) -> None: ...
def ConvAttributeAddAccType(builder: flatbuffers.Builder, accType: typing.Literal[DType.UNKNOWN, DType.BOOL, DType.UINT8, DType.INT4, DType.INT8, DType.INT16, DType.INT32, DType.INT48, DType.FP32, DType.UINT16, DType.FP16, DType.BF16, DType.SHAPE, DType.FP8E4M3, DType.FP8E5M2]) -> None: ...
def ConvAttributeEnd(builder: flatbuffers.Builder) -> uoffset: ...
class TransposeConvAttribute(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> TransposeConvAttribute: ...
  @classmethod
  def GetRootAsTransposeConvAttribute(cls, buf: bytes, offset: int) -> TransposeConvAttribute: ...
  @classmethod
  def TransposeConvAttributeBufferHasIdentifier(cls, buf: bytes, offset: int, size_prefixed: bool) -> bool: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def OutPad(self, i: int) -> typing.List[int]: ...
  def OutPadAsNumpy(self) -> np.ndarray: ...
  def OutPadLength(self) -> int: ...
  def OutPadIsNone(self) -> bool: ...
  def Stride(self, i: int) -> typing.List[int]: ...
  def StrideAsNumpy(self) -> np.ndarray: ...
  def StrideLength(self) -> int: ...
  def StrideIsNone(self) -> bool: ...
  def LocalBound(self) -> bool: ...
  def AccType(self) -> typing.Literal[DType.UNKNOWN, DType.BOOL, DType.UINT8, DType.INT4, DType.INT8, DType.INT16, DType.INT32, DType.INT48, DType.FP32, DType.UINT16, DType.FP16, DType.BF16, DType.SHAPE, DType.FP8E4M3, DType.FP8E5M2]: ...
class TransposeConvAttributeT(object):
  outPad: typing.List[int]
  stride: typing.List[int]
  localBound: bool
  accType: typing.Literal[DType.UNKNOWN, DType.BOOL, DType.UINT8, DType.INT4, DType.INT8, DType.INT16, DType.INT32, DType.INT48, DType.FP32, DType.UINT16, DType.FP16, DType.BF16, DType.SHAPE, DType.FP8E4M3, DType.FP8E5M2]
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> TransposeConvAttributeT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> TransposeConvAttributeT: ...
  @classmethod
  def InitFromObj(cls, transposeConvAttribute: TransposeConvAttribute) -> TransposeConvAttributeT: ...
  def _UnPack(self, transposeConvAttribute: TransposeConvAttribute) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def TransposeConvAttributeStart(builder: flatbuffers.Builder) -> None: ...
def TransposeConvAttributeAddOutPad(builder: flatbuffers.Builder, outPad: uoffset) -> None: ...
def TransposeConvAttributeStartOutPadVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def TransposeConvAttributeAddStride(builder: flatbuffers.Builder, stride: uoffset) -> None: ...
def TransposeConvAttributeStartStrideVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def TransposeConvAttributeAddLocalBound(builder: flatbuffers.Builder, localBound: bool) -> None: ...
def TransposeConvAttributeAddAccType(builder: flatbuffers.Builder, accType: typing.Literal[DType.UNKNOWN, DType.BOOL, DType.UINT8, DType.INT4, DType.INT8, DType.INT16, DType.INT32, DType.INT48, DType.FP32, DType.UINT16, DType.FP16, DType.BF16, DType.SHAPE, DType.FP8E4M3, DType.FP8E5M2]) -> None: ...
def TransposeConvAttributeEnd(builder: flatbuffers.Builder) -> uoffset: ...
class PadAttribute(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> PadAttribute: ...
  @classmethod
  def GetRootAsPadAttribute(cls, buf: bytes, offset: int) -> PadAttribute: ...
  @classmethod
  def PadAttributeBufferHasIdentifier(cls, buf: bytes, offset: int, size_prefixed: bool) -> bool: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def PadConst(self, i: int) -> typing.List[int]: ...
  def PadConstAsNumpy(self) -> np.ndarray: ...
  def PadConstLength(self) -> int: ...
  def PadConstIsNone(self) -> bool: ...
class PadAttributeT(object):
  padConst: typing.List[int]
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> PadAttributeT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> PadAttributeT: ...
  @classmethod
  def InitFromObj(cls, padAttribute: PadAttribute) -> PadAttributeT: ...
  def _UnPack(self, padAttribute: PadAttribute) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def PadAttributeStart(builder: flatbuffers.Builder) -> None: ...
def PadAttributeAddPadConst(builder: flatbuffers.Builder, padConst: uoffset) -> None: ...
def PadAttributeStartPadConstVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def PadAttributeEnd(builder: flatbuffers.Builder) -> uoffset: ...
class AxisAttribute(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> AxisAttribute: ...
  @classmethod
  def GetRootAsAxisAttribute(cls, buf: bytes, offset: int) -> AxisAttribute: ...
  @classmethod
  def AxisAttributeBufferHasIdentifier(cls, buf: bytes, offset: int, size_prefixed: bool) -> bool: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Axis(self) -> int: ...
  def NanMode(self) -> typing.Literal[NanPropagationMode.UNKNOWN, NanPropagationMode.PROPAGATE, NanPropagationMode.IGNORE]: ...
class AxisAttributeT(object):
  axis: int
  nanMode: typing.Literal[NanPropagationMode.UNKNOWN, NanPropagationMode.PROPAGATE, NanPropagationMode.IGNORE]
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> AxisAttributeT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> AxisAttributeT: ...
  @classmethod
  def InitFromObj(cls, axisAttribute: AxisAttribute) -> AxisAttributeT: ...
  def _UnPack(self, axisAttribute: AxisAttribute) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def AxisAttributeStart(builder: flatbuffers.Builder) -> None: ...
def AxisAttributeAddAxis(builder: flatbuffers.Builder, axis: int) -> None: ...
def AxisAttributeAddNanMode(builder: flatbuffers.Builder, nanMode: typing.Literal[NanPropagationMode.UNKNOWN, NanPropagationMode.PROPAGATE, NanPropagationMode.IGNORE]) -> None: ...
def AxisAttributeEnd(builder: flatbuffers.Builder) -> uoffset: ...
class ResizeAttribute(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> ResizeAttribute: ...
  @classmethod
  def GetRootAsResizeAttribute(cls, buf: bytes, offset: int) -> ResizeAttribute: ...
  @classmethod
  def ResizeAttributeBufferHasIdentifier(cls, buf: bytes, offset: int, size_prefixed: bool) -> bool: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Mode(self) -> typing.Literal[ResizeMode.UNKNOWN, ResizeMode.NEAREST, ResizeMode.BILINEAR]: ...
class ResizeAttributeT(object):
  mode: typing.Literal[ResizeMode.UNKNOWN, ResizeMode.NEAREST, ResizeMode.BILINEAR]
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> ResizeAttributeT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> ResizeAttributeT: ...
  @classmethod
  def InitFromObj(cls, resizeAttribute: ResizeAttribute) -> ResizeAttributeT: ...
  def _UnPack(self, resizeAttribute: ResizeAttribute) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def ResizeAttributeStart(builder: flatbuffers.Builder) -> None: ...
def ResizeAttributeAddMode(builder: flatbuffers.Builder, mode: typing.Literal[ResizeMode.UNKNOWN, ResizeMode.NEAREST, ResizeMode.BILINEAR]) -> None: ...
def ResizeAttributeEnd(builder: flatbuffers.Builder) -> uoffset: ...
class ClampAttribute(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> ClampAttribute: ...
  @classmethod
  def GetRootAsClampAttribute(cls, buf: bytes, offset: int) -> ClampAttribute: ...
  @classmethod
  def ClampAttributeBufferHasIdentifier(cls, buf: bytes, offset: int, size_prefixed: bool) -> bool: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def MinVal(self, i: int) -> typing.List[int]: ...
  def MinValAsNumpy(self) -> np.ndarray: ...
  def MinValLength(self) -> int: ...
  def MinValIsNone(self) -> bool: ...
  def MaxVal(self, i: int) -> typing.List[int]: ...
  def MaxValAsNumpy(self) -> np.ndarray: ...
  def MaxValLength(self) -> int: ...
  def MaxValIsNone(self) -> bool: ...
  def NanMode(self) -> typing.Literal[NanPropagationMode.UNKNOWN, NanPropagationMode.PROPAGATE, NanPropagationMode.IGNORE]: ...
class ClampAttributeT(object):
  minVal: typing.List[int]
  maxVal: typing.List[int]
  nanMode: typing.Literal[NanPropagationMode.UNKNOWN, NanPropagationMode.PROPAGATE, NanPropagationMode.IGNORE]
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> ClampAttributeT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> ClampAttributeT: ...
  @classmethod
  def InitFromObj(cls, clampAttribute: ClampAttribute) -> ClampAttributeT: ...
  def _UnPack(self, clampAttribute: ClampAttribute) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def ClampAttributeStart(builder: flatbuffers.Builder) -> None: ...
def ClampAttributeAddMinVal(builder: flatbuffers.Builder, minVal: uoffset) -> None: ...
def ClampAttributeStartMinValVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def ClampAttributeAddMaxVal(builder: flatbuffers.Builder, maxVal: uoffset) -> None: ...
def ClampAttributeStartMaxValVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def ClampAttributeAddNanMode(builder: flatbuffers.Builder, nanMode: typing.Literal[NanPropagationMode.UNKNOWN, NanPropagationMode.PROPAGATE, NanPropagationMode.IGNORE]) -> None: ...
def ClampAttributeEnd(builder: flatbuffers.Builder) -> uoffset: ...
class RescaleAttribute(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> RescaleAttribute: ...
  @classmethod
  def GetRootAsRescaleAttribute(cls, buf: bytes, offset: int) -> RescaleAttribute: ...
  @classmethod
  def RescaleAttributeBufferHasIdentifier(cls, buf: bytes, offset: int, size_prefixed: bool) -> bool: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def InputZp(self) -> int: ...
  def OutputZp(self) -> int: ...
  def Scale32(self) -> bool: ...
  def DoubleRound(self) -> bool: ...
  def PerChannel(self) -> bool: ...
  def InputUnsigned(self) -> bool: ...
  def OutputUnsigned(self) -> bool: ...
class RescaleAttributeT(object):
  inputZp: int
  outputZp: int
  scale32: bool
  doubleRound: bool
  perChannel: bool
  inputUnsigned: bool
  outputUnsigned: bool
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> RescaleAttributeT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> RescaleAttributeT: ...
  @classmethod
  def InitFromObj(cls, rescaleAttribute: RescaleAttribute) -> RescaleAttributeT: ...
  def _UnPack(self, rescaleAttribute: RescaleAttribute) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def RescaleAttributeStart(builder: flatbuffers.Builder) -> None: ...
def RescaleAttributeAddInputZp(builder: flatbuffers.Builder, inputZp: int) -> None: ...
def RescaleAttributeAddOutputZp(builder: flatbuffers.Builder, outputZp: int) -> None: ...
def RescaleAttributeAddScale32(builder: flatbuffers.Builder, scale32: bool) -> None: ...
def RescaleAttributeAddDoubleRound(builder: flatbuffers.Builder, doubleRound: bool) -> None: ...
def RescaleAttributeAddPerChannel(builder: flatbuffers.Builder, perChannel: bool) -> None: ...
def RescaleAttributeAddInputUnsigned(builder: flatbuffers.Builder, inputUnsigned: bool) -> None: ...
def RescaleAttributeAddOutputUnsigned(builder: flatbuffers.Builder, outputUnsigned: bool) -> None: ...
def RescaleAttributeEnd(builder: flatbuffers.Builder) -> uoffset: ...
class MulAttribute(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> MulAttribute: ...
  @classmethod
  def GetRootAsMulAttribute(cls, buf: bytes, offset: int) -> MulAttribute: ...
  @classmethod
  def MulAttributeBufferHasIdentifier(cls, buf: bytes, offset: int, size_prefixed: bool) -> bool: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Shift(self) -> int: ...
class MulAttributeT(object):
  shift: int
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> MulAttributeT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> MulAttributeT: ...
  @classmethod
  def InitFromObj(cls, mulAttribute: MulAttribute) -> MulAttributeT: ...
  def _UnPack(self, mulAttribute: MulAttribute) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def MulAttributeStart(builder: flatbuffers.Builder) -> None: ...
def MulAttributeAddShift(builder: flatbuffers.Builder, shift: int) -> None: ...
def MulAttributeEnd(builder: flatbuffers.Builder) -> uoffset: ...
class ArithmeticRightShiftAttribute(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> ArithmeticRightShiftAttribute: ...
  @classmethod
  def GetRootAsArithmeticRightShiftAttribute(cls, buf: bytes, offset: int) -> ArithmeticRightShiftAttribute: ...
  @classmethod
  def ArithmeticRightShiftAttributeBufferHasIdentifier(cls, buf: bytes, offset: int, size_prefixed: bool) -> bool: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Round(self) -> bool: ...
class ArithmeticRightShiftAttributeT(object):
  round: bool
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> ArithmeticRightShiftAttributeT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> ArithmeticRightShiftAttributeT: ...
  @classmethod
  def InitFromObj(cls, arithmeticRightShiftAttribute: ArithmeticRightShiftAttribute) -> ArithmeticRightShiftAttributeT: ...
  def _UnPack(self, arithmeticRightShiftAttribute: ArithmeticRightShiftAttribute) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def ArithmeticRightShiftAttributeStart(builder: flatbuffers.Builder) -> None: ...
def ArithmeticRightShiftAttributeAddRound(builder: flatbuffers.Builder, round: bool) -> None: ...
def ArithmeticRightShiftAttributeEnd(builder: flatbuffers.Builder) -> uoffset: ...
class CondIfAttribute(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> CondIfAttribute: ...
  @classmethod
  def GetRootAsCondIfAttribute(cls, buf: bytes, offset: int) -> CondIfAttribute: ...
  @classmethod
  def CondIfAttributeBufferHasIdentifier(cls, buf: bytes, offset: int, size_prefixed: bool) -> bool: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def ThenGraph(self) -> str | None: ...
  def ElseGraph(self) -> str | None: ...
class CondIfAttributeT(object):
  thenGraph: str | None
  elseGraph: str | None
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> CondIfAttributeT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> CondIfAttributeT: ...
  @classmethod
  def InitFromObj(cls, condIfAttribute: CondIfAttribute) -> CondIfAttributeT: ...
  def _UnPack(self, condIfAttribute: CondIfAttribute) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def CondIfAttributeStart(builder: flatbuffers.Builder) -> None: ...
def CondIfAttributeAddThenGraph(builder: flatbuffers.Builder, thenGraph: uoffset) -> None: ...
def CondIfAttributeAddElseGraph(builder: flatbuffers.Builder, elseGraph: uoffset) -> None: ...
def CondIfAttributeEnd(builder: flatbuffers.Builder) -> uoffset: ...
class WhileLoopAttribute(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> WhileLoopAttribute: ...
  @classmethod
  def GetRootAsWhileLoopAttribute(cls, buf: bytes, offset: int) -> WhileLoopAttribute: ...
  @classmethod
  def WhileLoopAttributeBufferHasIdentifier(cls, buf: bytes, offset: int, size_prefixed: bool) -> bool: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def CondGraph(self) -> str | None: ...
  def BodyGraph(self) -> str | None: ...
class WhileLoopAttributeT(object):
  condGraph: str | None
  bodyGraph: str | None
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> WhileLoopAttributeT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> WhileLoopAttributeT: ...
  @classmethod
  def InitFromObj(cls, whileLoopAttribute: WhileLoopAttribute) -> WhileLoopAttributeT: ...
  def _UnPack(self, whileLoopAttribute: WhileLoopAttribute) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def WhileLoopAttributeStart(builder: flatbuffers.Builder) -> None: ...
def WhileLoopAttributeAddCondGraph(builder: flatbuffers.Builder, condGraph: uoffset) -> None: ...
def WhileLoopAttributeAddBodyGraph(builder: flatbuffers.Builder, bodyGraph: uoffset) -> None: ...
def WhileLoopAttributeEnd(builder: flatbuffers.Builder) -> uoffset: ...
class TransposeAttribute(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> TransposeAttribute: ...
  @classmethod
  def GetRootAsTransposeAttribute(cls, buf: bytes, offset: int) -> TransposeAttribute: ...
  @classmethod
  def TransposeAttributeBufferHasIdentifier(cls, buf: bytes, offset: int, size_prefixed: bool) -> bool: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Perms(self, i: int) -> typing.List[int]: ...
  def PermsAsNumpy(self) -> np.ndarray: ...
  def PermsLength(self) -> int: ...
  def PermsIsNone(self) -> bool: ...
class TransposeAttributeT(object):
  perms: typing.List[int]
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> TransposeAttributeT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> TransposeAttributeT: ...
  @classmethod
  def InitFromObj(cls, transposeAttribute: TransposeAttribute) -> TransposeAttributeT: ...
  def _UnPack(self, transposeAttribute: TransposeAttribute) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def TransposeAttributeStart(builder: flatbuffers.Builder) -> None: ...
def TransposeAttributeAddPerms(builder: flatbuffers.Builder, perms: uoffset) -> None: ...
def TransposeAttributeStartPermsVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def TransposeAttributeEnd(builder: flatbuffers.Builder) -> uoffset: ...
class TableAttribute(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> TableAttribute: ...
  @classmethod
  def GetRootAsTableAttribute(cls, buf: bytes, offset: int) -> TableAttribute: ...
  @classmethod
  def TableAttributeBufferHasIdentifier(cls, buf: bytes, offset: int, size_prefixed: bool) -> bool: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
class TableAttributeT(object):
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> TableAttributeT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> TableAttributeT: ...
  @classmethod
  def InitFromObj(cls, tableAttribute: TableAttribute) -> TableAttributeT: ...
  def _UnPack(self, tableAttribute: TableAttribute) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def TableAttributeStart(builder: flatbuffers.Builder) -> None: ...
def TableAttributeEnd(builder: flatbuffers.Builder) -> uoffset: ...
class MatMulAttribute(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> MatMulAttribute: ...
  @classmethod
  def GetRootAsMatMulAttribute(cls, buf: bytes, offset: int) -> MatMulAttribute: ...
  @classmethod
  def MatMulAttributeBufferHasIdentifier(cls, buf: bytes, offset: int, size_prefixed: bool) -> bool: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def AZp(self) -> int: ...
  def BZp(self) -> int: ...
class MatMulAttributeT(object):
  aZp: int
  bZp: int
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> MatMulAttributeT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> MatMulAttributeT: ...
  @classmethod
  def InitFromObj(cls, matMulAttribute: MatMulAttribute) -> MatMulAttributeT: ...
  def _UnPack(self, matMulAttribute: MatMulAttribute) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def MatMulAttributeStart(builder: flatbuffers.Builder) -> None: ...
def MatMulAttributeAddAZp(builder: flatbuffers.Builder, aZp: int) -> None: ...
def MatMulAttributeAddBZp(builder: flatbuffers.Builder, bZp: int) -> None: ...
def MatMulAttributeEnd(builder: flatbuffers.Builder) -> uoffset: ...
class FullyConnectedAttribute(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> FullyConnectedAttribute: ...
  @classmethod
  def GetRootAsFullyConnectedAttribute(cls, buf: bytes, offset: int) -> FullyConnectedAttribute: ...
  @classmethod
  def FullyConnectedAttributeBufferHasIdentifier(cls, buf: bytes, offset: int, size_prefixed: bool) -> bool: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
class FullyConnectedAttributeT(object):
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> FullyConnectedAttributeT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> FullyConnectedAttributeT: ...
  @classmethod
  def InitFromObj(cls, fullyConnectedAttribute: FullyConnectedAttribute) -> FullyConnectedAttributeT: ...
  def _UnPack(self, fullyConnectedAttribute: FullyConnectedAttribute) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def FullyConnectedAttributeStart(builder: flatbuffers.Builder) -> None: ...
def FullyConnectedAttributeEnd(builder: flatbuffers.Builder) -> uoffset: ...
class NegateAttribute(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> NegateAttribute: ...
  @classmethod
  def GetRootAsNegateAttribute(cls, buf: bytes, offset: int) -> NegateAttribute: ...
  @classmethod
  def NegateAttributeBufferHasIdentifier(cls, buf: bytes, offset: int, size_prefixed: bool) -> bool: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Input1Zp(self) -> int: ...
  def OutputZp(self) -> int: ...
class NegateAttributeT(object):
  input1Zp: int
  outputZp: int
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> NegateAttributeT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> NegateAttributeT: ...
  @classmethod
  def InitFromObj(cls, negateAttribute: NegateAttribute) -> NegateAttributeT: ...
  def _UnPack(self, negateAttribute: NegateAttribute) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def NegateAttributeStart(builder: flatbuffers.Builder) -> None: ...
def NegateAttributeAddInput1Zp(builder: flatbuffers.Builder, input1Zp: int) -> None: ...
def NegateAttributeAddOutputZp(builder: flatbuffers.Builder, outputZp: int) -> None: ...
def NegateAttributeEnd(builder: flatbuffers.Builder) -> uoffset: ...
class CustomAttribute(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> CustomAttribute: ...
  @classmethod
  def GetRootAsCustomAttribute(cls, buf: bytes, offset: int) -> CustomAttribute: ...
  @classmethod
  def CustomAttributeBufferHasIdentifier(cls, buf: bytes, offset: int, size_prefixed: bool) -> bool: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def OperatorName(self) -> str | None: ...
  def DomainName(self) -> str | None: ...
  def ImplementationAttrs(self, i: int) -> typing.List[int]: ...
  def ImplementationAttrsAsNumpy(self) -> np.ndarray: ...
  def ImplementationAttrsLength(self) -> int: ...
  def ImplementationAttrsIsNone(self) -> bool: ...
class CustomAttributeT(object):
  operatorName: str | None
  domainName: str | None
  implementationAttrs: typing.List[int]
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> CustomAttributeT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> CustomAttributeT: ...
  @classmethod
  def InitFromObj(cls, customAttribute: CustomAttribute) -> CustomAttributeT: ...
  def _UnPack(self, customAttribute: CustomAttribute) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def CustomAttributeStart(builder: flatbuffers.Builder) -> None: ...
def CustomAttributeAddOperatorName(builder: flatbuffers.Builder, operatorName: uoffset) -> None: ...
def CustomAttributeAddDomainName(builder: flatbuffers.Builder, domainName: uoffset) -> None: ...
def CustomAttributeAddImplementationAttrs(builder: flatbuffers.Builder, implementationAttrs: uoffset) -> None: ...
def CustomAttributeStartImplementationAttrsVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def CustomAttributeEnd(builder: flatbuffers.Builder) -> uoffset: ...
class FFTAttribute(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> FFTAttribute: ...
  @classmethod
  def GetRootAsFFTAttribute(cls, buf: bytes, offset: int) -> FFTAttribute: ...
  @classmethod
  def FFTAttributeBufferHasIdentifier(cls, buf: bytes, offset: int, size_prefixed: bool) -> bool: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Inverse(self) -> bool: ...
  def LocalBound(self) -> bool: ...
class FFTAttributeT(object):
  inverse: bool
  localBound: bool
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> FFTAttributeT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> FFTAttributeT: ...
  @classmethod
  def InitFromObj(cls, fftattribute: FFTAttribute) -> FFTAttributeT: ...
  def _UnPack(self, fftattribute: FFTAttribute) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def FFTAttributeStart(builder: flatbuffers.Builder) -> None: ...
def FFTAttributeAddInverse(builder: flatbuffers.Builder, inverse: bool) -> None: ...
def FFTAttributeAddLocalBound(builder: flatbuffers.Builder, localBound: bool) -> None: ...
def FFTAttributeEnd(builder: flatbuffers.Builder) -> uoffset: ...
class RFFTAttribute(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> RFFTAttribute: ...
  @classmethod
  def GetRootAsRFFTAttribute(cls, buf: bytes, offset: int) -> RFFTAttribute: ...
  @classmethod
  def RFFTAttributeBufferHasIdentifier(cls, buf: bytes, offset: int, size_prefixed: bool) -> bool: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def LocalBound(self) -> bool: ...
class RFFTAttributeT(object):
  localBound: bool
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> RFFTAttributeT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> RFFTAttributeT: ...
  @classmethod
  def InitFromObj(cls, rfftattribute: RFFTAttribute) -> RFFTAttributeT: ...
  def _UnPack(self, rfftattribute: RFFTAttribute) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def RFFTAttributeStart(builder: flatbuffers.Builder) -> None: ...
def RFFTAttributeAddLocalBound(builder: flatbuffers.Builder, localBound: bool) -> None: ...
def RFFTAttributeEnd(builder: flatbuffers.Builder) -> uoffset: ...
class NanPropagationAttribute(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> NanPropagationAttribute: ...
  @classmethod
  def GetRootAsNanPropagationAttribute(cls, buf: bytes, offset: int) -> NanPropagationAttribute: ...
  @classmethod
  def NanPropagationAttributeBufferHasIdentifier(cls, buf: bytes, offset: int, size_prefixed: bool) -> bool: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def NanMode(self) -> typing.Literal[NanPropagationMode.UNKNOWN, NanPropagationMode.PROPAGATE, NanPropagationMode.IGNORE]: ...
class NanPropagationAttributeT(object):
  nanMode: typing.Literal[NanPropagationMode.UNKNOWN, NanPropagationMode.PROPAGATE, NanPropagationMode.IGNORE]
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> NanPropagationAttributeT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> NanPropagationAttributeT: ...
  @classmethod
  def InitFromObj(cls, nanPropagationAttribute: NanPropagationAttribute) -> NanPropagationAttributeT: ...
  def _UnPack(self, nanPropagationAttribute: NanPropagationAttribute) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def NanPropagationAttributeStart(builder: flatbuffers.Builder) -> None: ...
def NanPropagationAttributeAddNanMode(builder: flatbuffers.Builder, nanMode: typing.Literal[NanPropagationMode.UNKNOWN, NanPropagationMode.PROPAGATE, NanPropagationMode.IGNORE]) -> None: ...
def NanPropagationAttributeEnd(builder: flatbuffers.Builder) -> uoffset: ...
class Version(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> Version: ...
  @classmethod
  def GetRootAsVersion(cls, buf: bytes, offset: int) -> Version: ...
  @classmethod
  def VersionBufferHasIdentifier(cls, buf: bytes, offset: int, size_prefixed: bool) -> bool: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def _Major(self) -> int: ...
  def _Minor(self) -> int: ...
  def _Patch(self) -> int: ...
  def _Draft(self) -> bool: ...
class VersionT(object):
  _Major: int
  _Minor: int
  _Patch: int
  _Draft: bool
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> VersionT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> VersionT: ...
  @classmethod
  def InitFromObj(cls, version: Version) -> VersionT: ...
  def _UnPack(self, version: Version) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def VersionStart(builder: flatbuffers.Builder) -> None: ...
def VersionAdd_Major(builder: flatbuffers.Builder, _Major: int) -> None: ...
def VersionAdd_Minor(builder: flatbuffers.Builder, _Minor: int) -> None: ...
def VersionAdd_Patch(builder: flatbuffers.Builder, _Patch: int) -> None: ...
def VersionAdd_Draft(builder: flatbuffers.Builder, _Draft: bool) -> None: ...
def VersionEnd(builder: flatbuffers.Builder) -> uoffset: ...
class TosaTensor(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> TosaTensor: ...
  @classmethod
  def GetRootAsTosaTensor(cls, buf: bytes, offset: int) -> TosaTensor: ...
  @classmethod
  def TosaTensorBufferHasIdentifier(cls, buf: bytes, offset: int, size_prefixed: bool) -> bool: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Name(self) -> str | None: ...
  def Shape(self, i: int) -> typing.List[int]: ...
  def ShapeAsNumpy(self) -> np.ndarray: ...
  def ShapeLength(self) -> int: ...
  def ShapeIsNone(self) -> bool: ...
  def Type(self) -> typing.Literal[DType.UNKNOWN, DType.BOOL, DType.UINT8, DType.INT4, DType.INT8, DType.INT16, DType.INT32, DType.INT48, DType.FP32, DType.UINT16, DType.FP16, DType.BF16, DType.SHAPE, DType.FP8E4M3, DType.FP8E5M2]: ...
  def Data(self, i: int) -> typing.List[int]: ...
  def DataAsNumpy(self) -> np.ndarray: ...
  def DataLength(self) -> int: ...
  def DataIsNone(self) -> bool: ...
  def Variable(self) -> bool: ...
  def IsUnranked(self) -> bool: ...
  def VariableName(self) -> str | None: ...
class TosaTensorT(object):
  name: str | None
  shape: typing.List[int]
  type: typing.Literal[DType.UNKNOWN, DType.BOOL, DType.UINT8, DType.INT4, DType.INT8, DType.INT16, DType.INT32, DType.INT48, DType.FP32, DType.UINT16, DType.FP16, DType.BF16, DType.SHAPE, DType.FP8E4M3, DType.FP8E5M2]
  data: typing.List[int]
  variable: bool
  isUnranked: bool
  variableName: str | None
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> TosaTensorT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> TosaTensorT: ...
  @classmethod
  def InitFromObj(cls, tosaTensor: TosaTensor) -> TosaTensorT: ...
  def _UnPack(self, tosaTensor: TosaTensor) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def TosaTensorStart(builder: flatbuffers.Builder) -> None: ...
def TosaTensorAddName(builder: flatbuffers.Builder, name: uoffset) -> None: ...
def TosaTensorAddShape(builder: flatbuffers.Builder, shape: uoffset) -> None: ...
def TosaTensorStartShapeVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def TosaTensorAddType(builder: flatbuffers.Builder, type: typing.Literal[DType.UNKNOWN, DType.BOOL, DType.UINT8, DType.INT4, DType.INT8, DType.INT16, DType.INT32, DType.INT48, DType.FP32, DType.UINT16, DType.FP16, DType.BF16, DType.SHAPE, DType.FP8E4M3, DType.FP8E5M2]) -> None: ...
def TosaTensorAddData(builder: flatbuffers.Builder, data: uoffset) -> None: ...
def TosaTensorStartDataVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def TosaTensorAddVariable(builder: flatbuffers.Builder, variable: bool) -> None: ...
def TosaTensorAddIsUnranked(builder: flatbuffers.Builder, isUnranked: bool) -> None: ...
def TosaTensorAddVariableName(builder: flatbuffers.Builder, variableName: uoffset) -> None: ...
def TosaTensorEnd(builder: flatbuffers.Builder) -> uoffset: ...
class TosaOperator(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> TosaOperator: ...
  @classmethod
  def GetRootAsTosaOperator(cls, buf: bytes, offset: int) -> TosaOperator: ...
  @classmethod
  def TosaOperatorBufferHasIdentifier(cls, buf: bytes, offset: int, size_prefixed: bool) -> bool: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Op(self) -> typing.Literal[Op.UNKNOWN, Op.ARGMAX, Op.AVG_POOL2D, Op.CONV2D, Op.CONV3D, Op.DEPTHWISE_CONV2D, Op.FULLY_CONNECTED, Op.MATMUL, Op.MAX_POOL2D, Op.TRANSPOSE_CONV2D, Op.CLAMP, Op.RESERVED, Op.SIGMOID, Op.TANH, Op.ADD, Op.ARITHMETIC_RIGHT_SHIFT, Op.BITWISE_AND, Op.BITWISE_OR, Op.BITWISE_XOR, Op.INTDIV, Op.LOGICAL_AND, Op.LOGICAL_LEFT_SHIFT, Op.LOGICAL_RIGHT_SHIFT, Op.LOGICAL_OR, Op.LOGICAL_XOR, Op.MAXIMUM, Op.MINIMUM, Op.MUL, Op.POW, Op.SUB, Op.TABLE, Op.ABS, Op.BITWISE_NOT, Op.CEIL, Op.CLZ, Op.EXP, Op.FLOOR, Op.LOG, Op.LOGICAL_NOT, Op.NEGATE, Op.RECIPROCAL, Op.RSQRT, Op.SELECT, Op.EQUAL, Op.GREATER, Op.GREATER_EQUAL, Op.REDUCE_ANY, Op.REDUCE_ALL, Op.REDUCE_MAX, Op.REDUCE_MIN, Op.REDUCE_PRODUCT, Op.REDUCE_SUM, Op.CONCAT, Op.PAD, Op.RESHAPE, Op.REVERSE, Op.SLICE, Op.TILE, Op.TRANSPOSE, Op.GATHER, Op.SCATTER, Op.RESIZE, Op.CAST, Op.RESCALE, Op.CONST, Op.IDENTITY, Op.CUSTOM, Op.COND_IF, Op.WHILE_LOOP, Op.FFT2D, Op.RFFT2D, Op.ERF, Op.DIM, Op.CONST_SHAPE, Op.CONCAT_SHAPE, Op.ADD_SHAPE, Op.SUB_SHAPE, Op.MUL_SHAPE, Op.DIV_SHAPE, Op.COS, Op.SIN]: ...
  def AttributeType(self) -> typing.Literal[Attribute.NONE, Attribute.PoolAttribute, Attribute.ConvAttribute, Attribute.TransposeConvAttribute, Attribute.PadAttribute, Attribute.AxisAttribute, Attribute.ResizeAttribute, Attribute.ClampAttribute, Attribute.RescaleAttribute, Attribute.MulAttribute, Attribute.ArithmeticRightShiftAttribute, Attribute.CondIfAttribute, Attribute.WhileLoopAttribute, Attribute.TransposeAttribute, Attribute.TableAttribute, Attribute.MatMulAttribute, Attribute.FullyConnectedAttribute, Attribute.NegateAttribute, Attribute.CustomAttribute, Attribute.FFTAttribute, Attribute.RFFTAttribute, Attribute.NanPropagationAttribute]: ...
  def Attribute(self) -> table.Table | None: ...
  def Inputs(self, i: int) -> str: ...
  def InputsLength(self) -> int: ...
  def InputsIsNone(self) -> bool: ...
  def Outputs(self, i: int) -> str: ...
  def OutputsLength(self) -> int: ...
  def OutputsIsNone(self) -> bool: ...
class TosaOperatorT(object):
  op: typing.Literal[Op.UNKNOWN, Op.ARGMAX, Op.AVG_POOL2D, Op.CONV2D, Op.CONV3D, Op.DEPTHWISE_CONV2D, Op.FULLY_CONNECTED, Op.MATMUL, Op.MAX_POOL2D, Op.TRANSPOSE_CONV2D, Op.CLAMP, Op.RESERVED, Op.SIGMOID, Op.TANH, Op.ADD, Op.ARITHMETIC_RIGHT_SHIFT, Op.BITWISE_AND, Op.BITWISE_OR, Op.BITWISE_XOR, Op.INTDIV, Op.LOGICAL_AND, Op.LOGICAL_LEFT_SHIFT, Op.LOGICAL_RIGHT_SHIFT, Op.LOGICAL_OR, Op.LOGICAL_XOR, Op.MAXIMUM, Op.MINIMUM, Op.MUL, Op.POW, Op.SUB, Op.TABLE, Op.ABS, Op.BITWISE_NOT, Op.CEIL, Op.CLZ, Op.EXP, Op.FLOOR, Op.LOG, Op.LOGICAL_NOT, Op.NEGATE, Op.RECIPROCAL, Op.RSQRT, Op.SELECT, Op.EQUAL, Op.GREATER, Op.GREATER_EQUAL, Op.REDUCE_ANY, Op.REDUCE_ALL, Op.REDUCE_MAX, Op.REDUCE_MIN, Op.REDUCE_PRODUCT, Op.REDUCE_SUM, Op.CONCAT, Op.PAD, Op.RESHAPE, Op.REVERSE, Op.SLICE, Op.TILE, Op.TRANSPOSE, Op.GATHER, Op.SCATTER, Op.RESIZE, Op.CAST, Op.RESCALE, Op.CONST, Op.IDENTITY, Op.CUSTOM, Op.COND_IF, Op.WHILE_LOOP, Op.FFT2D, Op.RFFT2D, Op.ERF, Op.DIM, Op.CONST_SHAPE, Op.CONCAT_SHAPE, Op.ADD_SHAPE, Op.SUB_SHAPE, Op.MUL_SHAPE, Op.DIV_SHAPE, Op.COS, Op.SIN]
  attributeType: typing.Literal[Attribute.NONE, Attribute.PoolAttribute, Attribute.ConvAttribute, Attribute.TransposeConvAttribute, Attribute.PadAttribute, Attribute.AxisAttribute, Attribute.ResizeAttribute, Attribute.ClampAttribute, Attribute.RescaleAttribute, Attribute.MulAttribute, Attribute.ArithmeticRightShiftAttribute, Attribute.CondIfAttribute, Attribute.WhileLoopAttribute, Attribute.TransposeAttribute, Attribute.TableAttribute, Attribute.MatMulAttribute, Attribute.FullyConnectedAttribute, Attribute.NegateAttribute, Attribute.CustomAttribute, Attribute.FFTAttribute, Attribute.RFFTAttribute, Attribute.NanPropagationAttribute]
  attribute: typing.Union[None, PoolAttributeT, ConvAttributeT, TransposeConvAttributeT, PadAttributeT, AxisAttributeT, ResizeAttributeT, ClampAttributeT, RescaleAttributeT, MulAttributeT, ArithmeticRightShiftAttributeT, CondIfAttributeT, WhileLoopAttributeT, TransposeAttributeT, TableAttributeT, MatMulAttributeT, FullyConnectedAttributeT, NegateAttributeT, CustomAttributeT, FFTAttributeT, RFFTAttributeT, NanPropagationAttributeT]
  inputs: typing.List[str]
  outputs: typing.List[str]
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> TosaOperatorT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> TosaOperatorT: ...
  @classmethod
  def InitFromObj(cls, tosaOperator: TosaOperator) -> TosaOperatorT: ...
  def _UnPack(self, tosaOperator: TosaOperator) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def TosaOperatorStart(builder: flatbuffers.Builder) -> None: ...
def TosaOperatorAddOp(builder: flatbuffers.Builder, op: typing.Literal[Op.UNKNOWN, Op.ARGMAX, Op.AVG_POOL2D, Op.CONV2D, Op.CONV3D, Op.DEPTHWISE_CONV2D, Op.FULLY_CONNECTED, Op.MATMUL, Op.MAX_POOL2D, Op.TRANSPOSE_CONV2D, Op.CLAMP, Op.RESERVED, Op.SIGMOID, Op.TANH, Op.ADD, Op.ARITHMETIC_RIGHT_SHIFT, Op.BITWISE_AND, Op.BITWISE_OR, Op.BITWISE_XOR, Op.INTDIV, Op.LOGICAL_AND, Op.LOGICAL_LEFT_SHIFT, Op.LOGICAL_RIGHT_SHIFT, Op.LOGICAL_OR, Op.LOGICAL_XOR, Op.MAXIMUM, Op.MINIMUM, Op.MUL, Op.POW, Op.SUB, Op.TABLE, Op.ABS, Op.BITWISE_NOT, Op.CEIL, Op.CLZ, Op.EXP, Op.FLOOR, Op.LOG, Op.LOGICAL_NOT, Op.NEGATE, Op.RECIPROCAL, Op.RSQRT, Op.SELECT, Op.EQUAL, Op.GREATER, Op.GREATER_EQUAL, Op.REDUCE_ANY, Op.REDUCE_ALL, Op.REDUCE_MAX, Op.REDUCE_MIN, Op.REDUCE_PRODUCT, Op.REDUCE_SUM, Op.CONCAT, Op.PAD, Op.RESHAPE, Op.REVERSE, Op.SLICE, Op.TILE, Op.TRANSPOSE, Op.GATHER, Op.SCATTER, Op.RESIZE, Op.CAST, Op.RESCALE, Op.CONST, Op.IDENTITY, Op.CUSTOM, Op.COND_IF, Op.WHILE_LOOP, Op.FFT2D, Op.RFFT2D, Op.ERF, Op.DIM, Op.CONST_SHAPE, Op.CONCAT_SHAPE, Op.ADD_SHAPE, Op.SUB_SHAPE, Op.MUL_SHAPE, Op.DIV_SHAPE, Op.COS, Op.SIN]) -> None: ...
def TosaOperatorAddAttributeType(builder: flatbuffers.Builder, attributeType: typing.Literal[Attribute.NONE, Attribute.PoolAttribute, Attribute.ConvAttribute, Attribute.TransposeConvAttribute, Attribute.PadAttribute, Attribute.AxisAttribute, Attribute.ResizeAttribute, Attribute.ClampAttribute, Attribute.RescaleAttribute, Attribute.MulAttribute, Attribute.ArithmeticRightShiftAttribute, Attribute.CondIfAttribute, Attribute.WhileLoopAttribute, Attribute.TransposeAttribute, Attribute.TableAttribute, Attribute.MatMulAttribute, Attribute.FullyConnectedAttribute, Attribute.NegateAttribute, Attribute.CustomAttribute, Attribute.FFTAttribute, Attribute.RFFTAttribute, Attribute.NanPropagationAttribute]) -> None: ...
def TosaOperatorAddAttribute(builder: flatbuffers.Builder, attribute: uoffset) -> None: ...
def TosaOperatorAddInputs(builder: flatbuffers.Builder, inputs: uoffset) -> None: ...
def TosaOperatorStartInputsVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def TosaOperatorAddOutputs(builder: flatbuffers.Builder, outputs: uoffset) -> None: ...
def TosaOperatorStartOutputsVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def TosaOperatorEnd(builder: flatbuffers.Builder) -> uoffset: ...
class TosaBasicBlock(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> TosaBasicBlock: ...
  @classmethod
  def GetRootAsTosaBasicBlock(cls, buf: bytes, offset: int) -> TosaBasicBlock: ...
  @classmethod
  def TosaBasicBlockBufferHasIdentifier(cls, buf: bytes, offset: int, size_prefixed: bool) -> bool: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Name(self) -> str | None: ...
  def Operators(self, i: int) -> TosaOperator | None: ...
  def OperatorsLength(self) -> int: ...
  def OperatorsIsNone(self) -> bool: ...
  def Tensors(self, i: int) -> TosaTensor | None: ...
  def TensorsLength(self) -> int: ...
  def TensorsIsNone(self) -> bool: ...
  def Inputs(self, i: int) -> str: ...
  def InputsLength(self) -> int: ...
  def InputsIsNone(self) -> bool: ...
  def Outputs(self, i: int) -> str: ...
  def OutputsLength(self) -> int: ...
  def OutputsIsNone(self) -> bool: ...
class TosaBasicBlockT(object):
  name: str | None
  operators: typing.List[TosaOperatorT]
  tensors: typing.List[TosaTensorT]
  inputs: typing.List[str]
  outputs: typing.List[str]
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> TosaBasicBlockT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> TosaBasicBlockT: ...
  @classmethod
  def InitFromObj(cls, tosaBasicBlock: TosaBasicBlock) -> TosaBasicBlockT: ...
  def _UnPack(self, tosaBasicBlock: TosaBasicBlock) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def TosaBasicBlockStart(builder: flatbuffers.Builder) -> None: ...
def TosaBasicBlockAddName(builder: flatbuffers.Builder, name: uoffset) -> None: ...
def TosaBasicBlockAddOperators(builder: flatbuffers.Builder, operators: uoffset) -> None: ...
def TosaBasicBlockStartOperatorsVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def TosaBasicBlockAddTensors(builder: flatbuffers.Builder, tensors: uoffset) -> None: ...
def TosaBasicBlockStartTensorsVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def TosaBasicBlockAddInputs(builder: flatbuffers.Builder, inputs: uoffset) -> None: ...
def TosaBasicBlockStartInputsVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def TosaBasicBlockAddOutputs(builder: flatbuffers.Builder, outputs: uoffset) -> None: ...
def TosaBasicBlockStartOutputsVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def TosaBasicBlockEnd(builder: flatbuffers.Builder) -> uoffset: ...
class TosaRegion(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> TosaRegion: ...
  @classmethod
  def GetRootAsTosaRegion(cls, buf: bytes, offset: int) -> TosaRegion: ...
  @classmethod
  def TosaRegionBufferHasIdentifier(cls, buf: bytes, offset: int, size_prefixed: bool) -> bool: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Name(self) -> str | None: ...
  def Blocks(self, i: int) -> TosaBasicBlock | None: ...
  def BlocksLength(self) -> int: ...
  def BlocksIsNone(self) -> bool: ...
class TosaRegionT(object):
  name: str | None
  blocks: typing.List[TosaBasicBlockT]
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> TosaRegionT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> TosaRegionT: ...
  @classmethod
  def InitFromObj(cls, tosaRegion: TosaRegion) -> TosaRegionT: ...
  def _UnPack(self, tosaRegion: TosaRegion) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def TosaRegionStart(builder: flatbuffers.Builder) -> None: ...
def TosaRegionAddName(builder: flatbuffers.Builder, name: uoffset) -> None: ...
def TosaRegionAddBlocks(builder: flatbuffers.Builder, blocks: uoffset) -> None: ...
def TosaRegionStartBlocksVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def TosaRegionEnd(builder: flatbuffers.Builder) -> uoffset: ...
class TosaGraph(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> TosaGraph: ...
  @classmethod
  def GetRootAsTosaGraph(cls, buf: bytes, offset: int) -> TosaGraph: ...
  @classmethod
  def TosaGraphBufferHasIdentifier(cls, buf: bytes, offset: int, size_prefixed: bool) -> bool: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Version(self) -> Version | None: ...
  def Regions(self, i: int) -> TosaRegion | None: ...
  def RegionsLength(self) -> int: ...
  def RegionsIsNone(self) -> bool: ...
class TosaGraphT(object):
  version: VersionT | None
  regions: typing.List[TosaRegionT]
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> TosaGraphT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> TosaGraphT: ...
  @classmethod
  def InitFromObj(cls, tosaGraph: TosaGraph) -> TosaGraphT: ...
  def _UnPack(self, tosaGraph: TosaGraph) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def TosaGraphStart(builder: flatbuffers.Builder) -> None: ...
def TosaGraphAddVersion(builder: flatbuffers.Builder, version: uoffset) -> None: ...
def TosaGraphAddRegions(builder: flatbuffers.Builder, regions: uoffset) -> None: ...
def TosaGraphStartRegionsVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def TosaGraphEnd(builder: flatbuffers.Builder) -> uoffset: ...

